const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process'),P=require('pptxgenjs');
const root=path.resolve(__dirname,'..','..','..');
const fig=path.join(root,'report','0417_5003report','figures','paper_figures');
const scriptSrc=path.join(__dirname,'final_15min_script.md');
const C={b:'223A5E',bd:'16263F',bs:'A6404B',c:'F7F5F1',g:'E8EEF5',w:'FFFFFF',i:'1E2630',s:'667085',m:'D9DEE7'};
const H='Times New Roman',B='Times New Roman';
const slide2={headline:{x:.65,y:.84,w:6,h:.58,fontSize:17.2},cards:{x:.65,y:1.48,w:2.7,h:2.48,gap:.3},callout:{x:7.18,y:4.18,w:2.12,h:.82}};
const outDir=(()=>{const i=process.argv.indexOf('--output-dir');return i>0&&process.argv[i+1]?path.resolve(process.argv[i+1]):__dirname;})();
fs.mkdirSync(outDir,{recursive:true});
fs.copyFileSync(scriptSrc,path.join(outDir,'final_15min_script.md'));
function sanitizePptxPackage(filePath){
  const tempRoot=fs.mkdtempSync(path.join(os.tmpdir(),'pptx-sanitize-'));
  const zipPath=path.join(tempRoot,'deck.zip');
  const unpackDir=path.join(tempRoot,'unpacked');
  const repackedZip=path.join(tempRoot,'deck-fixed.zip');
  try{
    fs.copyFileSync(filePath,zipPath);
    execFileSync('powershell',['-NoProfile','-Command',`Expand-Archive -LiteralPath '${zipPath}' -DestinationPath '${unpackDir}' -Force`],{stdio:'pipe'});
    const contentTypesPath=path.join(unpackDir,'[Content_Types].xml');
    let xml=fs.readFileSync(contentTypesPath,'utf8');
    xml=xml.replace(/<Override PartName="([^"]+)" ContentType="([^"]+)"\/>/g,(m,partName,contentType)=>{
      const rel=partName.replace(/^\//,'').replace(/\//g,path.sep);
      return fs.existsSync(path.join(unpackDir,rel))?m:'';
    });
    fs.writeFileSync(contentTypesPath,xml,'utf8');
    execFileSync('powershell',['-NoProfile','-Command',`Compress-Archive -Path (Join-Path '${unpackDir}' '*') -DestinationPath '${repackedZip}' -Force`],{stdio:'pipe'});
    fs.copyFileSync(repackedZip,filePath);
  }finally{
    fs.rmSync(tempRoot,{recursive:true,force:true});
  }
}
const ppt=new P(); ppt.layout='LAYOUT_16x9'; ppt.author='OpenAI Codex'; ppt.title='EE5003 Final Presentation'; ppt.subject='Adversarial Deletion Attacks on Approximate Graph Unlearning';
const txt=(s,t,o)=>s.addText(t,{fontFace:B,fontSize:13,color:C.i,margin:0,...o});
const frame=(s,n,t)=>{s.addShape('rect',{x:0,y:0,w:10,h:.58,fill:{color:C.b},line:{color:C.b,transparency:100}});txt(s,t,{x:.55,y:.11,w:7.2,h:.24,fontFace:H,fontSize:24,bold:true,color:C.w});txt(s,`${String(n).padStart(2,'0')} / 15`,{x:8.7,y:.13,w:.7,h:.15,fontSize:10,color:C.c,align:'right'});txt(s,'EE5003 MSc Project | Liu Chengyu',{x:.55,y:5.18,w:3,h:.15,fontSize:9,color:C.s});txt(s,'Approximate Graph Unlearning Audit',{x:6.1,y:5.18,w:3.3,h:.15,fontSize:9,color:C.s,align:'right'});};
const card=(s,x,y,w,h,t,b,f=C.w,tc=C.b,bc=C.i)=>{s.addShape('roundRect',{x,y,w,h,rectRadius:.05,fill:{color:f},line:{color:f===C.w?C.m:f,width:1.1}});txt(s,t,{x:x+.15,y:y+.1,w:w-.3,h:.2,fontFace:H,fontSize:17,bold:true,color:tc});txt(s,b,{x:x+.15,y:y+.37,w:w-.3,h:h-.47,fontSize:12.2,color:bc,fit:'shrink'});};
const stat=(s,x,y,w,h,v,l,f=C.b,vc=C.w,lc=C.c)=>{s.addShape('roundRect',{x,y,w,h,rectRadius:.05,fill:{color:f},line:{color:f,transparency:100}});txt(s,v,{x:x+.08,y:y+.12,w:w-.16,h:.22,fontFace:H,fontSize:19,bold:true,color:vc,align:'center'});txt(s,l,{x:x+.08,y:y+.42,w:w-.16,h:h-.47,fontSize:10,color:lc,align:'center',fit:'shrink'});};
let s=ppt.addSlide(); s.background={color:C.bd}; s.addShape('rect',{x:6.95,y:0,w:3.05,h:5.625,fill:{color:C.g,transparency:12},line:{color:C.g,transparency:100}}); txt(s,'Adversarial Deletion Attacks on\nApproximate Graph Unlearning',{x:.75,y:.82,w:5.7,h:1.3,fontFace:H,fontSize:24,bold:true,color:C.w,fit:'shrink'}); txt(s,'The inheritance of safety behavior within graph unlearning families',{x:.78,y:2.3,w:5,h:.3,fontSize:15,italic:true,color:C.c}); txt(s,'EE5003 MSc Project Report\nNational University of Singapore',{x:.78,y:3.2,w:3.6,h:.5,fontSize:15,color:C.c}); txt(s,'Liu Chengyu\nApril 2026',{x:.78,y:4,w:2.1,h:.4,fontSize:14,color:C.w}); card(s,7.08,1.3,2.15,1.8,'Thesis','Deletion interfaces in approximate graph unlearning can be exploited to amplify approximation error, and fragility differs sharply across method families.',C.w,C.bd); [['Problem',7.12,3.45,C.w,C.bd],['Method',8.24,3.45,C.g,C.b],['Results',7.12,3.98,C.g,C.b],['Takeaway',8.24,3.98,C.w,C.bd]].forEach(a=>{s.addShape('roundRect',{x:a[1],y:a[2],w:.96,h:.34,rectRadius:.04,fill:{color:a[3]},line:{color:a[3]===C.w?C.m:a[3],width:1}}); txt(s,a[0],{x:a[1]+.04,y:a[2]+.08,w:.88,h:.12,fontFace:H,fontSize:11.2,bold:true,color:a[4],align:'center'});});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,2,'Why Graph Unlearning Matters'); txt(s,'Deletion requests are operationally plausible, and approximation turns them into a security question.',{x:slide2.headline.x,y:slide2.headline.y,w:slide2.headline.w,h:slide2.headline.h,fontFace:H,fontSize:slide2.headline.fontSize,bold:true,color:C.b,fit:'shrink'}); [['Real deletion requests','User-level or node-level removal is realistic in citation, social, and recommendation graphs.'],['Approximate\nunlearning','Exact retraining is expensive, so practical systems use approximation.'],['Attack surface','A malicious requester may exploit the deletion interface itself by choosing harmful targets.']].forEach((a,i)=>{const x=slide2.cards.x+i*(slide2.cards.w+slide2.cards.gap),y=slide2.cards.y,w=slide2.cards.w,h=slide2.cards.h; s.addShape('roundRect',{x,y,w,h,rectRadius:.05,fill:{color:C.w},line:{color:C.m,width:1.1}}); txt(s,a[0],{x:x+.15,y:y+.12,w:w-.3,h:.46,fontFace:H,fontSize:15.8,bold:true,color:C.b,fit:'shrink'}); txt(s,a[1],{x:x+.15,y:y+1.12,w:w-.3,h:h-1.27,fontSize:11.8,color:C.i,fit:'shrink'});}); stat(s,slide2.callout.x,slide2.callout.y,slide2.callout.w,slide2.callout.h,'Delete','Compliance tool and attack interface',C.bs);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,3,'Research Question And Objectives'); card(s,.7,1,8.6,.95,'Research question','Can malicious deletion requests amplify approximation error and degrade retained-model utility beyond ordinary deletion at the same budget?',C.b,C.c,C.w); [['Objective 1','Build an attack pipeline with multiple deletion strategies.'],['Objective 2','Compare vulnerability across method families, not just one algorithm.'],['Objective 3','Add attribution metrics for collateral and retrain gap.'],['Objective 4','Measure whether adversarial node selection is practically efficient.']].forEach((a,i)=>card(s,.85+(i%2)*4.25,2.35+Math.floor(i/2)*1.25,3.95,.98,a[0],a[1],i===0?C.g:C.w));
s=ppt.addSlide(); s.background={color:C.c}; frame(s,4,'Method Families And Threat Model'); txt(s,'Families under test',{x:.7,y:.82,w:2.4,h:.2,fontFace:H,fontSize:19,bold:true,color:C.b}); card(s,.72,1.15,3.15,1.05,'Learning-based','Learn a direct unlearning correction; GNNDelete is the fragile representative here.'); card(s,.72,2.35,3.15,1.05,'IF-based','Approximate deletion through local influence-style updates; GIF stays comparatively stable.'); card(s,.72,3.55,3.15,1.05,'Shard-based','Partition the graph and retrain affected shards; GraphEraser behaves differently in the tested settings.',C.g); card(s,4.3,1.15,4.95,2.1,'Threat model','Attacker capability: choose which nodes to delete through the normal interface.\n\nOut of scope: poisoning labels, features, or hidden training code.\n\nTarget: maximize post-unlearning utility loss beyond random deletion.',C.b,C.c,C.w); stat(s,4.45,3.65,1.35,.78,'ΔF1','attack-over-random'); stat(s,6.05,3.65,1.35,.78,'Gap','vs exact retrain',C.bs); stat(s,7.65,3.65,1.35,.78,'26.2%','non-target changes',C.g,C.b,C.b);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,5,'Attack Pipeline And Experimental Matrix'); txt(s,'The workflow compares approximate unlearning against an exact-retrain control on the same deletion set.',{x:.68,y:.84,w:7.3,h:.25,fontFace:H,fontSize:18,bold:true,color:C.b}); [['1','Select nodes','Use random or structured attack targets.',C.b],['2','Apply unlearning','Run the selected graph unlearning method.',C.bs],['3','Exact retrain control','Retrain on the same deletions for the gold-standard reference.',C.g],['4','Compare outcomes','Read utility loss, retrain gap, and collateral damage.',C.i]].forEach((a,i)=>{const y=1.48+i*.95; s.addShape('roundRect',{x:.75,y,w:4.1,h:.75,rectRadius:.05,fill:{color:C.w},line:{color:C.m,width:1.1}}); s.addShape('ellipse',{x:.9,y:y+.15,w:.42,h:.42,fill:{color:a[3]},line:{color:a[3],transparency:100}}); txt(s,a[0],{x:.9,y:y+.21,w:.42,h:.12,fontSize:13.2,bold:true,color:a[3]===C.g?C.b:C.w,align:'center'}); txt(s,a[1],{x:1.47,y:y+.1,w:3.15,h:.16,fontFace:H,fontSize:15.5,bold:true,color:C.b}); txt(s,a[2],{x:1.47,y:y+.34,w:3.15,h:.22,fontSize:11.3,color:C.i,fit:'shrink'});}); card(s,5.25,1.5,3.95,3.58,'Experimental matrix','Methods: 5\nDatasets: 2 citation graphs\nBackbones: 3 GNN architectures\nStrategies: 6 node-selection methods\nRuns: 950 experiment executions\n\nOutputs: relative_f1_drop, retrain_gap, collateral damage, and efficiency.',C.w);
s=ppt.addSlide(); s.background={color:C.c}; frame(s,6,'Attack Selection Logic'); txt(s,'The attack is not only about how many nodes are deleted, but about what logic is used to choose them.',{x:.68,y:.84,w:8.1,h:.28,fontFace:H,fontSize:16.6,bold:true,color:C.b}); card(s,.78,1.45,2.72,2.22,'TracIn / IF-style','Model-aware logic.\nPick nodes with high training influence on the learned model.\n\nShorthand: score(v) ≈ I_train(v)',C.w); card(s,3.64,1.45,2.72,2.22,'IM','Graph-structural logic.\nPick nodes that maximize spread or disruption in the graph.\n\nShorthand: score(S) = spread(S)',C.g); card(s,6.5,1.45,2.72,2.22,'Hybrid','Combine model-side influence with topology-side spread to search for stronger targets.\n\nShorthand: score(v) = α·z_IF(v) + (1-α)·z_IM(v)',C.w); card(s,1.18,4.16,7.56,.76,'Reading rule','Read these formulas only as intuition. The benchmark compares attacker logics: model-aware selection, graph-structural selection, and a hybrid of the two.',C.b,C.c,C.w);
s=ppt.addSlide(); s.background={color:C.c}; frame(s,7,'Metrics Framework'); txt(s,'Three metrics answer three different questions: how much extra damage appears beyond a k=5 baseline, where it comes from, and how far it spreads.',{x:.68,y:.84,w:8.1,h:.28,fontFace:H,fontSize:16.2,bold:true,color:C.b}); card(s,.78,1.45,2.78,2.2,'Utility','relative_f1_drop = F1_after(k=5, random) - F1_after(attack)\n\nUse a tiny random-trigger baseline because raw drop can mislead on shard-based methods.',C.w); card(s,3.64,1.45,2.78,2.2,'Fidelity','retrain_gap = F1_retrain - F1_unlearn\n\ntotal_drop = drop_retrain + retrain_gap',C.g); card(s,6.5,1.45,2.78,2.2,'Collateral','fraction_flipped\nmean_pred_shift\n\nThese show how strongly retained nodes are disturbed.',C.w); card(s,1.08,4.14,7.76,.84,'Reading rule','First trigger each method with a tiny random deletion, k=5, and use that post-unlearning F1 as the reference point. Then compare stronger attacks against that baseline; retrain_gap and collateral metrics explain why the utility changes appear.',C.b,C.c,C.w);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,8,'Main Finding: Family Spectrum'); s.addImage({path:path.join(fig,'FIG-1_Generalization.png'),x:.6,y:1,w:5.45,h:3.45}); txt(s,'Figure 1. Family-level spectrum using relative F1 drop at ratio = 0.05.',{x:.62,y:4.58,w:5.4,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.18,1.02,3.05,1.0,'Core read','Relative_f1_drop reveals a family-level vulnerability spectrum rather than one shared failure pattern.',C.b,C.c,C.w); card(s,6.18,2.18,3.05,1.08,'Family readout','GNNDelete highest.\nGIF comparatively stable.\nGraphEraser shows shard protection.',C.w,C.bs,C.i); card(s,6.18,3.46,3.05,1.18,'Strategy readout','Across the same figure family and the companion strategy view, the strongest extra damage still concentrates on GNNDelete rather than spreading evenly across methods.',C.g,C.b,C.i);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,9,'Main Finding: Strategy Spectrum'); s.addImage({path:path.join(fig,'FIG-3_Spectrum.png'),x:.72,y:1.02,w:8.55,h:3.9}); txt(s,'Full Figure 3. Strategy comparison in relative_f1_drop at ratio = 0.05 using the k=5 baseline.',{x:.78,y:5.02,w:8.25,h:.16,fontSize:9,italic:true,color:C.s});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,10,'Ratio Sensitivity And Ablation'); s.addImage({path:path.join(fig,'FIG-2_Scaling.png'),x:.62,y:1,w:5.75,h:3.6}); txt(s,'Figure 2. Ratio-sensitivity view for GIF and GNNDelete on Cora/GCN.',{x:.64,y:4.7,w:5.7,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.58,1.1,2.58,1.05,'Ablation read','This page asks how attack strength changes as the deletion ratio increases, not only who wins at one fixed point.',C.w); card(s,6.58,2.45,2.58,1.05,'Observed pattern','GNNDelete stays sensitive even at small ratios, while GIF remains much flatter across the same range.',C.g); card(s,6.58,3.8,2.58,.82,'Takeaway','The family difference is structural rather than a one-point artifact of the chosen ratio.',C.b,C.c,C.w);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,11,'Attribution And Collateral Damage'); txt(s,'relative_f1_drop says the attack beats the k=5 method baseline; retrain_gap and collateral metrics explain where the extra damage comes from.',{x:.68,y:.84,w:8.2,h:.25,fontFace:H,fontSize:16.7,bold:true,color:C.b}); card(s,.78,1.5,2.72,2.78,'Attack success','relative_f1_drop tells us whether a structured attack causes more loss than the small random-trigger baseline.',C.w); card(s,3.65,1.5,2.72,2.78,'Attribution','retrain_gap isolates the additional approximation error by comparing approximate unlearning with exact retraining on the same deletion set.',C.g); card(s,6.52,1.5,2.72,2.78,'Spillover','fraction_flipped and mean_pred_shift show how strongly retained non-target nodes are disturbed.',C.w); s.addShape('roundRect',{x:1.48,y:4.32,w:7.02,h:.84,rectRadius:.05,fill:{color:C.b},line:{color:C.b,transparency:100}}); txt(s,'Bottom line',{x:1.66,y:4.45,w:1.35,h:.18,fontFace:H,fontSize:13.8,bold:true,color:C.c}); txt(s,'If total_drop = drop_retrain + retrain_gap, then large retrain gaps and large retained-node shifts indicate mechanism-induced spillover rather than only intrinsic node importance.',{x:1.66,y:4.72,w:6.62,h:.28,fontSize:11,color:C.c,fit:'shrink'});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,12,'GraphEraser And Shard Protection'); s.addImage({path:path.join(root,'report','0417_5003report','figures','report_figures','fig2_grapheraser_shard.png'),x:.68,y:1.12,w:5.25,h:3.72}); txt(s,'Observed shard-level score shift for GraphEraser on Cora/GCN.',{x:.72,y:4.88,w:5.15,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.2,1.15,2.95,.98,'Observed pattern','After-unlearning scores shift upward across the tested strategies, which is evidence for a shard protection effect in these settings.',C.g); card(s,6.2,2.35,2.95,1.16,'Why it matters','This is why raw utility drop alone is not the right cross-family metric here; the k=5 relative baseline is the cleaner comparison lens.',C.w); card(s,6.2,3.85,2.95,.95,'Caution','This remains setting-specific evidence, not a claim of universal robustness.',C.bs,C.w,C.w);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,13,'Statistical Support And Effect Size'); s.addImage({path:path.join(fig,'FIG-4a_Significance.png'),x:.58,y:1.02,w:4.15,h:3.32}); s.addImage({path:path.join(fig,'FIG-4b_Effect.png'),x:5.2,y:1.02,w:4.15,h:3.32}); txt(s,'Figure 4a. Statistical support against random deletion.',{x:.6,y:4.46,w:4.08,h:.16,fontSize:9,italic:true,color:C.s}); txt(s,'Figure 4b. Effect size beyond random deletion.',{x:5.22,y:4.46,w:4.08,h:.16,fontSize:9,italic:true,color:C.s}); card(s,.9,4.78,3.55,.42,'Support','Figure 4a asks how strongly the attack-over-random difference is supported.',C.w); card(s,5.45,4.78,3.55,.42,'Effect','Figure 4b asks how large that extra damage is once support is established.',C.g);
s=ppt.addSlide(); s.background={color:C.c}; frame(s,14,'Limitations And Future Work'); txt(s,'The project is complete; these scope limits and follow-up directions define what this report does and does not claim.',{x:.68,y:.84,w:8.2,h:.25,fontFace:H,fontSize:17.5,bold:true,color:C.b}); [['Limitation 1','Evidence is concentrated on the tested citation benchmarks and backbones.'],['Limitation 2','The mechanism-level explanation for GNNDelete fragility is still incomplete.']].forEach((a,i)=>card(s,.82,1.52+i*1.42,2.95,1.12,a[0],a[1])); [['Future work 1','Validate the same pattern on larger graph benchmarks such as PubMed.'],['Future work 2','Add targeted ablations that explain when and why GNNDelete fails.']].forEach((a,i)=>card(s,4.05,1.52+i*1.42,2.95,1.12,a[0],a[1],C.w)); s.addShape('roundRect',{x:7.12,y:1.96,w:1.95,h:1.55,rectRadius:.05,fill:{color:C.b},line:{color:C.b,transparency:100}}); txt(s,'Project status',{x:7.28,y:2.08,w:1.62,h:.18,fontFace:H,fontSize:13.8,bold:true,color:C.c}); txt(s,'Completed MSc project\nFinal course submission with a reusable audit workflow.',{x:7.28,y:2.36,w:1.62,h:.95,fontSize:10.4,color:C.c,fit:'shrink'});
s=ppt.addSlide(); s.background={color:C.bd}; txt(s,'Takeaways',{x:.7,y:.72,w:2.2,h:.3,fontFace:H,fontSize:28,bold:true,color:C.w}); card(s,.85,1.45,2.55,2.4,'1. Auditability matters','Approximate graph unlearning should be evaluated not only for accuracy but also for adversarial deletion robustness.',C.w,C.bd); card(s,3.72,1.45,2.55,2.4,'2. Family behavior differs','In the tested settings, GNNDelete is most fragile, GIF is comparatively stable, and GraphEraser exhibits shard protection.',C.w,C.bs); card(s,6.59,1.45,2.55,2.4,'3. Workflow contribution','The project contributes a reusable OpenGU-based audit pipeline alongside the findings themselves.',C.g,C.b,C.i); txt(s,'Thank you. Q&A',{x:.78,y:4.55,w:8.5,h:.3,fontFace:H,fontSize:24,bold:true,color:C.w,align:'center'}); txt(s,'EE5003 MSc Project | Liu Chengyu',{x:.72,y:5.12,w:2.5,h:.15,fontSize:9,color:C.c});
const pptxPath=path.join(outDir,'final_15min_defense.pptx');
ppt.writeFile({fileName:pptxPath}).then(()=>{/*sanitizePptxPackage(pptxPath);*/process.stdout.write(`Generated presentation assets in ${outDir}\n`)}).catch(e=>{console.error(e);process.exitCode=1;});




