const fs=require('node:fs'),path=require('node:path'),P=require('pptxgenjs');
const root=path.resolve(__dirname,'..','..','..');
const fig=path.join(root,'report','0417_5003report','figures','paper_figures');
const scriptSrc=path.join(__dirname,'final_15min_script.md');
const C={b:'223A5E',bd:'16263F',bs:'A6404B',c:'F7F5F1',g:'E8EEF5',w:'FFFFFF',i:'1E2630',s:'667085',m:'D9DEE7'};
const H='Georgia',B='Calibri';
const outDir=(()=>{const i=process.argv.indexOf('--output-dir');return i>0&&process.argv[i+1]?path.resolve(process.argv[i+1]):__dirname;})();
fs.mkdirSync(outDir,{recursive:true});
fs.copyFileSync(scriptSrc,path.join(outDir,'final_15min_script.md'));
const ppt=new P(); ppt.layout='LAYOUT_16x9'; ppt.author='OpenAI Codex'; ppt.title='EE5003 Final Presentation'; ppt.subject='Adversarial Deletion Attacks on Approximate Graph Unlearning';
const txt=(s,t,o)=>s.addText(t,{fontFace:B,fontSize:13,color:C.i,margin:0,...o});
const frame=(s,n,t)=>{s.addShape('rect',{x:0,y:0,w:10,h:.58,fill:{color:C.b},line:{color:C.b,transparency:100}});txt(s,t,{x:.55,y:.11,w:7.2,h:.24,fontFace:H,fontSize:24,bold:true,color:C.w});txt(s,`${String(n).padStart(2,'0')} / 14`,{x:8.7,y:.13,w:.7,h:.15,fontSize:10,color:C.c,align:'right'});txt(s,'EE5003 MSc Project | Liu Chengyu',{x:.55,y:5.18,w:3,h:.15,fontSize:9,color:C.s});txt(s,'Approximate Graph Unlearning Audit',{x:6.1,y:5.18,w:3.3,h:.15,fontSize:9,color:C.s,align:'right'});};
const card=(s,x,y,w,h,t,b,f=C.w,tc=C.b,bc=C.i)=>{s.addShape('roundRect',{x,y,w,h,rectRadius:.05,fill:{color:f},line:{color:f===C.w?C.m:f,width:1.1}});txt(s,t,{x:x+.15,y:y+.1,w:w-.3,h:.2,fontFace:H,fontSize:17,bold:true,color:tc});txt(s,b,{x:x+.15,y:y+.37,w:w-.3,h:h-.47,fontSize:12.2,color:bc,fit:'shrink'});};
const stat=(s,x,y,w,h,v,l,f=C.b,vc=C.w,lc=C.c)=>{s.addShape('roundRect',{x,y,w,h,rectRadius:.05,fill:{color:f},line:{color:f,transparency:100}});txt(s,v,{x:x+.08,y:y+.12,w:w-.16,h:.22,fontFace:H,fontSize:19,bold:true,color:vc,align:'center'});txt(s,l,{x:x+.08,y:y+.42,w:w-.16,h:h-.47,fontSize:10,color:lc,align:'center',fit:'shrink'});};
let s=ppt.addSlide(); s.background={color:C.bd}; s.addShape('rect',{x:6.95,y:0,w:3.05,h:5.625,fill:{color:C.g,transparency:12},line:{color:C.g,transparency:100}}); txt(s,'Adversarial Deletion Attacks on\nApproximate Graph Unlearning',{x:.75,y:.82,w:5.7,h:1.3,fontFace:H,fontSize:24,bold:true,color:C.w,fit:'shrink'}); txt(s,'The inheritance of safety behavior within graph unlearning families',{x:.78,y:2.3,w:5,h:.3,fontSize:15,italic:true,color:C.c}); txt(s,'EE5003 MSc Project Report\nNational University of Singapore',{x:.78,y:3.2,w:3.6,h:.5,fontSize:15,color:C.c}); txt(s,'Liu Chengyu\nApril 2026',{x:.78,y:4,w:2.1,h:.4,fontSize:14,color:C.w}); card(s,6.95,1.1,2.25,2,'Thesis','Deletion interfaces in approximate graph unlearning can be exploited to amplify approximation error, and fragility differs sharply across method families.',C.w,C.bd); txt(s,'Problem -> Method -> Results -> Takeaway',{x:6.9,y:3.56,w:2.3,h:.2,fontSize:12,color:C.b,align:'center'});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,2,'Why Graph Unlearning Matters'); txt(s,'Deletion requests are operationally plausible, and approximation turns them into a security question.',{x:.65,y:.84,w:6.2,h:.25,fontFace:H,fontSize:19,bold:true,color:C.b}); card(s,.65,1.4,2.7,2.95,'Real deletion requests','User-level or node-level removal is realistic in citation, social, and recommendation graphs.'); card(s,3.65,1.4,2.7,2.95,'Approximate unlearning','Exact retraining is expensive, so practical systems use approximation.'); card(s,6.65,1.4,2.7,2.95,'Attack surface','A malicious requester may exploit the deletion interface itself by choosing harmful targets.'); stat(s,7.2,4.55,1.95,.62,'Delete','Compliance tool and attack interface',C.bs);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,3,'Research Question And Objectives'); card(s,.7,1,8.6,.95,'Research question','Can malicious deletion requests amplify approximation error and degrade retained-model utility beyond ordinary deletion at the same budget?',C.b,C.c,C.w); [['Objective 1','Build an attack pipeline with multiple deletion strategies.'],['Objective 2','Compare vulnerability across method families, not just one algorithm.'],['Objective 3','Add attribution metrics for collateral and retrain gap.'],['Objective 4','Measure whether adversarial node selection is practically efficient.']].forEach((a,i)=>card(s,.85+(i%2)*4.25,2.35+Math.floor(i/2)*1.25,3.95,.98,a[0],a[1],i===0?C.g:C.w));
s=ppt.addSlide(); s.background={color:C.c}; frame(s,4,'Method Families And Threat Model'); txt(s,'Families under test',{x:.7,y:.82,w:2.4,h:.2,fontFace:H,fontSize:19,bold:true,color:C.b}); card(s,.72,1.15,3.15,1.05,'Learning-based','GNNDelete is the main fragile representative in this study.'); card(s,.72,2.35,3.15,1.05,'IF-based','GIF remains comparatively stable under adversarial selection.'); card(s,.72,3.55,3.15,1.05,'Shard-based','GraphEraser behaves differently and often improves in the tested settings.',C.g); card(s,4.3,1.15,4.95,2.1,'Threat model','Attacker capability: choose which nodes to delete through the normal interface.\n\nOut of scope: poisoning labels, features, or hidden training code.\n\nTarget: maximize post-unlearning utility loss beyond random deletion.',C.b,C.c,C.w); stat(s,4.45,3.65,1.35,.78,'ΔF1','attack-over-random'); stat(s,6.05,3.65,1.35,.78,'Gap','vs exact retrain',C.bs); stat(s,7.65,3.65,1.35,.78,'26.2%','non-target changes',C.g,C.b,C.b);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,5,'Attack Pipeline And Experimental Matrix'); txt(s,'The workflow compares approximate unlearning against an exact-retrain control on the same deletion set.',{x:.68,y:.84,w:7.3,h:.25,fontFace:H,fontSize:18,bold:true,color:C.b}); [['1','Select nodes','Use random or structured attack targets.',C.b],['2','Apply unlearning','Run the selected graph unlearning method.',C.bs],['3','Exact retrain control','Retrain on the same deletions for the gold-standard reference.',C.g],['4','Compare outcomes','Read utility loss, retrain gap, and collateral damage.',C.i]].forEach((a,i)=>{const y=1.48+i*.95; s.addShape('roundRect',{x:.75,y,w:4.1,h:.75,rectRadius:.05,fill:{color:C.w},line:{color:C.m,width:1.1}}); s.addShape('ellipse',{x:.9,y:y+.15,w:.42,h:.42,fill:{color:a[3]},line:{color:a[3],transparency:100}}); txt(s,a[0],{x:.9,y:y+.21,w:.42,h:.12,fontSize:13.2,bold:true,color:a[3]===C.g?C.b:C.w,align:'center'}); txt(s,a[1],{x:1.47,y:y+.1,w:3.15,h:.16,fontFace:H,fontSize:15.5,bold:true,color:C.b}); txt(s,a[2],{x:1.47,y:y+.34,w:3.15,h:.22,fontSize:11.3,color:C.i,fit:'shrink'});}); card(s,5.25,1.5,3.95,3.58,'Experimental matrix','Methods: 5\nDatasets: 2 citation graphs\nBackbones: 3 GNN architectures\nStrategies: 6 node-selection methods\nRuns: 950 experiment executions\n\nStory: spectrum, deep dive, attribution, and efficiency.',C.w);
s=ppt.addSlide(); s.background={color:C.c}; frame(s,6,'What Was Built In OpenGU'); txt(s,'The project contribution is a reusable adversarial-audit workflow, not only a single batch of experiments.',{x:.68,y:.84,w:7.3,h:.25,fontFace:H,fontSize:18,bold:true,color:C.b}); [['Execution','Structured batch experiment runs across methods, datasets, and deletion ratios.'],['Result discovery','Auto-discovery of stored outputs to reduce manual bookkeeping.'],['Collateral analysis','Retained-node prediction tracking to reveal spillover.'],['Statistical summary','Relative F1 drop, support thresholds, and effect-size comparisons.'],['Figure generation','Reusable plotting scripts that turn stored outputs into report figures.']].forEach((a,i)=>card(s,.8+(i%2)*4.4,1.45+Math.floor(i/2)*1.08,4,.9,a[0],a[1])); stat(s,7.25,4.5,1.75,.62,'Reproducible','analysis from stored outputs',C.b);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,7,'Main Finding: Vulnerability Spectrum'); s.addImage({path:path.join(fig,'FIG-1_Generalization.png'),x:.6,y:1,w:5.8,h:3.7}); txt(s,'Figure 1. Relative F1 drop across datasets and backbones at ratio = 0.05.',{x:.62,y:4.8,w:5.75,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.7,1.02,2.6,1.18,'Core read','Approximate graph unlearning does not fail uniformly. Vulnerability depends strongly on the mechanism family.',C.b,C.c,C.w); card(s,6.72,2.42,2.55,1.0,'Readout','GNNDelete highest.\nGIF comparatively stable.\nGraphEraser shows no collapse.',C.w,C.bs,C.i); s.addText([{text:'The family-level pattern is consistent across the tested settings.',options:{bullet:{indent:16},breakLine:true}},{text:'Mechanism choice, not just deletion budget, determines fragility.',options:{bullet:{indent:16}}}],{x:6.84,y:3.78,w:2.1,h:.95,fontFace:B,fontSize:11.6,color:C.i,margin:0,paraSpaceAfterPt:8});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,8,'Deep Dive: GNNDelete Fragility'); s.addImage({path:path.join(fig,'FIG-2_Scaling.png'),x:.62,y:1,w:5.75,h:3.6}); txt(s,'Figure 2. Ratio sensitivity view for GIF and GNNDelete on Cora/GCN.',{x:.64,y:4.7,w:5.7,h:.16,fontSize:9,italic:true,color:C.s}); stat(s,6.75,1.2,2.1,.8,'21.53%','retrain gap at ratio 0.01 on Cora',C.bs); stat(s,6.75,2.2,2.1,.8,'26.2%','non-target prediction changes',C.b); card(s,6.55,3.25,2.55,1.45,'Interpretation','Exact retraining on the same deletion set shows only a small intrinsic decrease. The large collapse is therefore mainly approximation error, not simply node importance.');
s=ppt.addSlide(); s.background={color:C.w}; frame(s,9,'Attribution And Collateral Damage'); txt(s,'Exact retraining tells us what the deletion should have done. The remaining gap is mechanism-induced spillover.',{x:.68,y:.84,w:8.2,h:.25,fontFace:H,fontSize:18,bold:true,color:C.b}); card(s,.78,1.5,3.95,2.85,'Deleted targets','Some drop is legitimate because removed nodes can be informative. A correct system may still lose a small amount of utility when those nodes disappear. ',C.w); card(s,5.1,1.5,3.95,2.85,'Retained nodes','When predictions on non-target retained nodes shift substantially, the damage is no longer only about the deleted nodes. It indicates spillover from the approximate unlearning mechanism.',C.w); card(s,1.65,4.55,6.65,.55,'Bottom line','Approximate unlearning vs exact retrain is the attribution lens; collateral-damage metrics show how far the error propagates beyond the requested deletion.',C.b,C.c,C.w);
s=ppt.addSlide(); s.background={color:C.c}; frame(s,10,'Why GraphEraser Behaves Differently'); s.addImage({path:path.join(root,'report','0417_5003report','figures','report_figures','fig2_grapheraser_shard.png'),x:.68,y:1.12,w:5.25,h:3.72}); txt(s,'Observed shard-level score shift for GraphEraser on Cora/GCN.',{x:.72,y:4.88,w:5.15,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.2,1.15,2.95,.98,'Observed pattern','After-unlearning scores shift upward across the tested attack strategies, matching the non-collapse pattern seen in the main results.',C.g); card(s,6.2,2.35,2.95,1.25,'Interpretation','A plausible reading is that deleting bridge or hub nodes can simplify shard-local classification and reduce cross-shard interference.',C.w); card(s,6.2,3.92,2.95,.88,'Caution','This is setting-specific evidence, not a claim of universal robustness.',C.bs,C.w,C.w);
s=ppt.addSlide(); s.background={color:C.w}; frame(s,11,'Attack Strength And Practicality'); s.addImage({path:path.join(fig,'FIG-3_Spectrum.png'),x:.6,y:1,w:5.85,h:3.7}); txt(s,'Figure 3. Cross-family comparison of the main attack strategies at ratio = 0.05.',{x:.63,y:4.8,w:5.8,h:.16,fontSize:9,italic:true,color:C.s}); card(s,6.72,1,2.55,.95,'Reading key','Relative F1 drop measures the attack-over-random advantage at the same budget.',C.w); stat(s,6.78,2.18,1.05,1.0,'18.9s','IM-v4 selection time',C.b); stat(s,7.98,2.18,1.05,1.0,'1.3%','spread loss vs CELF',C.g,C.b,C.b); card(s,6.78,3.35,2.25,.72,'Practical','Selection is operationally feasible.',C.w); s.addText([{text:'Structured attacks outperform random deletion most clearly on GNNDelete.',options:{bullet:{indent:16},breakLine:true}},{text:'IM-v4 makes attack selection fast enough to matter in practice.',options:{bullet:{indent:16}}}],{x:6.84,y:4.3,w:2.1,h:.65,fontFace:B,fontSize:11.2,color:C.i,margin:0,paraSpaceAfterPt:8});
s=ppt.addSlide(); s.background={color:C.c}; frame(s,12,'Limitations And Future Work'); txt(s,'The project is complete; these scope limits and follow-up directions define what this report does and does not claim.',{x:.68,y:.84,w:8.2,h:.25,fontFace:H,fontSize:17.5,bold:true,color:C.b}); [['Limitation 1','Evidence is concentrated on the tested citation benchmarks and backbones.'],['Limitation 2','The mechanism-level explanation for GNNDelete fragility is still incomplete.']].forEach((a,i)=>card(s,.82,1.52+i*1.42,2.95,1.12,a[0],a[1])); [['Future work 1','Validate the same pattern on larger graph benchmarks such as PubMed.'],['Future work 2','Add targeted ablations that explain when and why GNNDelete fails.']].forEach((a,i)=>card(s,4.05,1.52+i*1.42,2.95,1.12,a[0],a[1],C.w)); s.addShape('roundRect',{x:7.12,y:1.96,w:1.95,h:1.55,rectRadius:.05,fill:{color:C.b},line:{color:C.b,transparency:100}}); txt(s,'Project status',{x:7.28,y:2.08,w:1.62,h:.18,fontFace:H,fontSize:13.8,bold:true,color:C.c}); txt(s,'Completed MSc project\nFinal course submission with a reusable audit workflow.',{x:7.28,y:2.36,w:1.62,h:.95,fontSize:10.4,color:C.c,fit:'shrink'});
s=ppt.addSlide(); s.background={color:C.bd}; txt(s,'Takeaways',{x:.7,y:.72,w:2.2,h:.3,fontFace:H,fontSize:28,bold:true,color:C.w}); card(s,.85,1.45,2.55,2.4,'1. Auditability matters','Approximate graph unlearning should be evaluated not only for accuracy but also for adversarial deletion robustness.',C.w,C.bd); card(s,3.72,1.45,2.55,2.4,'2. Family behavior differs','In the tested settings, GNNDelete is most fragile, GIF is comparatively stable, and GraphEraser exhibits shard protection.',C.w,C.bs); card(s,6.59,1.45,2.55,2.4,'3. Workflow contribution','The project contributes a reusable OpenGU-based audit pipeline alongside the findings themselves.',C.g,C.b,C.i); txt(s,'Thank you. Q&A',{x:.78,y:4.55,w:8.5,h:.3,fontFace:H,fontSize:24,bold:true,color:C.w,align:'center'}); txt(s,'EE5003 MSc Project | Liu Chengyu',{x:.72,y:5.12,w:2.5,h:.15,fontSize:9,color:C.c});
s=ppt.addSlide(); s.background={color:C.w}; frame(s,14,'Backup Appendix: Statistical Support'); s.addImage({path:path.join(fig,'FIG-4a_Significance.png'),x:.6,y:1.1,w:4.15,h:3.45}); s.addImage({path:path.join(fig,'FIG-4b_Effect.png'),x:5.15,y:1.1,w:4.15,h:3.45}); txt(s,'Figure 4a. -log10(p) support against random deletion.',{x:.62,y:4.7,w:4.1,h:.16,fontSize:9,italic:true,color:C.s}); txt(s,'Figure 4b. Effect size beyond random deletion.',{x:5.17,y:4.7,w:4.1,h:.16,fontSize:9,italic:true,color:C.s});
ppt.writeFile({fileName:path.join(outDir,'final_15min_defense.pptx')}).then(()=>process.stdout.write(`Generated presentation assets in ${outDir}\n`)).catch(e=>{console.error(e);process.exitCode=1;});




